services:

  postgres:
    container_name: "postgres"
    image: postgres
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "admin"

  frontend:
    container_name: "frontend"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    restart: unless-stopped
    ports:
      - 3001:3001
    volumes:
      - ./frontend:/app/
    networks:
      - app-network

  backend:
    container_name: "backend"
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    restart: unless-stopped
    ports:
      - 3200:3200
    volumes:
      - ./backend:/app
    networks:
      - app-network
    depends_on:
      - postgres

networks:
  app-network:
    driver: bridge
